name: store_app
description: "A new Flutter project."
publish_to: 'none' # Không publish lên pub.dev (nếu muốn public thì xóa dòng này)

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter                      # SDK chính để phát triển ứng dụng Flutter
  cupertino_icons: ^1.0.8             # Bộ icon theo phong cách iOS (Cupertino)
  google_fonts: ^6.2.1                # Dùng font chữ từ Google Fonts
  get: ^4.6.6                         # Quản lý trạng thái, điều hướng và dependency injection
  get_storage: ^2.1.1                 # Lưu trữ dữ liệu cục bộ (local storage) nhẹ, nhanh
  share_plus: ^12.0.0                 # Chia sẻ nội dung (text, link, hình...) qua ứng dụng khác
  flutter_facebook_auth: ^7.1.2       # Đăng nhập bằng tài khoản Facebook
  google_sign_in: ^7.2.0              # Đăng nhập bằng tài khoản Google
  firebase_core: ^4.2.0               # Cấu hình Firebase cho ứng dụng Flutter
  cloud_firestore: ^6.0.3             # Sử dụng cơ sở dữ liệu đám mây Firestore
  firebase_auth: ^6.1.1               # Xác thực người dùng qua Firebase (email, Google, Facebook...)
  url_launcher: ^6.3.0                # Mở URL, gọi điện, gửi email, mở bản đồ... từ app
  http: ^1.2.2                        # Gửi và nhận request HTTP (GET, POST,...)
  file_picker: ^10.3.3                # Chọn file từ bộ nhớ thiết bị
  cached_network_image: ^3.3.1        # Hiển thị ảnh mạng có bộ nhớ đệm (cache)
  shimmer: ^3.0.0                     # Hiệu ứng shimmer (loading placeholder)
  badges: ^3.1.2                      # Hiển thị huy hiệu (badge) cho icon, ví dụ thông báo
  intl: ^0.20.2                       # Xử lý định dạng ngày, số, ngôn ngữ quốc tế
  lottie: ^3.0.0                      # Hiển thị animation JSON (Lottie)
  mobile_scanner: ^7.1.3              # Quét mã QR và mã vạch bằng camera
  qr_flutter: ^4.1.0                  # Tạo mã QR từ dữ liệu
  google_maps_flutter: ^2.9.0         # Tích hợp Google Maps trong ứng dụng
  timeline_tile: ^2.0.0               # Tạo giao diện timeline (dòng thời gian)
  geolocator: ^14.0.2                 # Lấy vị trí GPS, tính khoảng cách, theo dõi vị trí
  image_picker: ^1.0.7                # Chọn ảnh/video từ thư viện hoặc chụp bằng camera

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0               # Bộ quy tắc lint giúp viết code tốt hơn

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
